version: '3'
services:
  client:
    image: node:18
    container_name: client
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - api

  api:
    # image to build container from
    image: node:18
    container_name: server
    # expose a container port to a local port
    ports:
      - 3000:3000
    # where is the code and how we access it
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    # what to do once the container has started
    command: bash -c "npm install && npm run dev"